/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_jyj_jnivideo_VideoPlayer */

#ifndef _Included_com_example_jyj_jnivideo_VideoPlayer
#define _Included_com_example_jyj_jnivideo_VideoPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_jyj_jnivideo_VideoPlayer
 * Method:    render
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_jyj_jnivideo_VideoPlayer_render
  (JNIEnv *, jobject, jstring,jobject);

#ifdef __cplusplus
}
#endif
#endif
